AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  integrify-report-to-csv

  SAM Template for integrify-report-to-csv
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ReportToCsvFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: report-to-csv/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      FunctionName: integrify-report-to-csv
      Description: "Report-To-CSV: Runs a report and attaches the results as a CSV file to the completed Lambda task."
      Role: arn:aws:iam::564858915116:role/PublicLambdaAccess
      Architectures:
        - x86_64
     
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ReportToCsvFunction:
    Description: "Report To CSV Function ARN"
    Value: !GetAtt ReportToCsvFunction.Arn
  