AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  integrify-exec-js

  Sample SAM Template for integrify-exec-js
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ExecJsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: exec-js/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      FunctionName: ExecJs
      Description: "Execute Javascript Function"
      Role: arn:aws:iam::564858915116:role/PublicLambdaAccess  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
 
  ExecJsFunction:
    Description: "Execute Javascript Function ARN"
    Value: !GetAtt ExecJsFunction.Arn
